-- Onboarding documents bucket
--
-- Private bucket for driver onboarding documents (licences, IDs, utility
-- bills, etc.). Objects are only accessible via signed URLs generated by
-- the server. RLS ensures drivers can only upload/read their own files.

begin;

-- Create the bucket (if not exists)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'onboarding-documents',
  'onboarding-documents',
  false,
  10485760, -- 10MB
  array['image/jpeg', 'image/jpg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do update set
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = array['image/jpeg', 'image/jpg', 'image/png', 'image/webp', 'application/pdf'];

-- RLS policies for the bucket.
-- Path convention: {user_id}/{document_type}/{filename}
--   e.g. 3c010183-.../licence_front/abc.jpg

drop policy if exists onboarding_docs_driver_upload on storage.objects;
create policy onboarding_docs_driver_upload on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'onboarding-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists onboarding_docs_driver_read on storage.objects;
create policy onboarding_docs_driver_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'onboarding-documents'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or exists (
        select 1 from user_roles
        where user_id = auth.uid()
          and role in ('admin_verifier', 'admin_support', 'super_admin')
      )
    )
  );

drop policy if exists onboarding_docs_driver_update on storage.objects;
create policy onboarding_docs_driver_update on storage.objects
  for update to authenticated
  using (
    bucket_id = 'onboarding-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists onboarding_docs_driver_delete on storage.objects;
create policy onboarding_docs_driver_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'onboarding-documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Ensure onboarding_state jsonb exists on driver_profiles
alter table driver_profiles
  add column if not exists onboarding_state jsonb not null default '{}'::jsonb,
  add column if not exists onboarding_submitted_at timestamptz;

commit;
